#!/bin/bash
 
# check for -f flag as first argument; if present, bypass all restrictions
if [[ "$1" == "-f" ]]; then
	shift
	git-commit "$@"
	exit 0
fi
 
fail()
{
	echo ==========================
	echo -e $1
	echo ==========================
	exit 1
}
 
# copy args so that $@ can be shifted but we can pass all args to git-merge
args=$@
 
# Determine whether this is the Dataraptor proj.
# If so, impose constraints. If not, skip to execution.
if [[ -r "config/application.rb" && ! -z $(grep Clu2 "config/application.rb") ]]; then
 
	# determine current branch
	dst=$(git status | grep "On branch" | cut -d " " -f 4)
	if [[ "$dst" =~ ^(develop|master)$ ]]; then
		# Allow commit on merge (i.e. revision has more than one parent)
		if [[ -f ".git/MERGE_MSG" ]]; then
			shift
			args=$@
		else
			fail "You cannot commit to develop or master.\nCommit to a fix or feature branch instead."
		fi
	fi
 
	# Forbid commit if diff contains a pry
	git diff --cached | egrep -q "\+.*binding\.pry" && {
		fail "You cannot commit 'binding.pry' to source control.\nRun \`git diff --cached | egrep -l \"\+.*binding\.pry\"\`"
	}
	# Forbid commit if diff contains debugger
	git diff --cached | egrep -q "\+.*debugger" && {
		fail "You cannot commit 'debugger' to source control.\nRun \`git diff --cached | egrep -l \"\+.*debugger\"\`"
	}
 
fi
 
# Execute merge
git-commit "$args"